---
- name: "Check for required inventory springboot_application_name variable"
  fail:
    msg: springboot_application_name variable is required and should be defined in you inventory
  when: not springboot_application_name or springboot_application_name == ''

- name: "Check for required inventory springboot_application_name variable"
  fail:
    msg: springboot_src variable is required and should be defined in you inventory
  when: not springboot_src or springboot_src == ''

- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"

- name: "Install java"
  include: java.yml

- name: "Create group for springboot app"
  group:
    name: "{{ springboot_group }}"
    state: present

- name: "Create user for springboot app"
  user:
    name: "{{ springboot_user }}"
    group: "{{ springboot_group }}"
    state: present

- name: "Copy jar application"
  copy:
    src: "{{ springboot_src }}"
    dest: "{{ springboot_target }}"
    owner: "{{ springboot_user }}"
    group: "{{ springboot_group }}"
    mode: "u+x"

- name: Install as service
  include: service.yml
